[package]
name = "pinitd-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
pinitd-common = { path = "../pinitd-common" }

clap = { version = "4.5", features = ["derive"] }
tokio = { version = "1.44", features = ["full"] }
bincode = { version = "2.0" }
thiserror = "2.0"
