name: Release on Push

on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r28c
          add-to-path: true
          link-to-sdk: true

      - name: Install cargo-ndk
        run: cargo install cargo-ndk

      - name: Build Rust binaries
        run: cargo ndk -t arm64-v8a build --release

      - name: Copy pinitd into APK build location
        run: |
          mkdir -p android/app/src/main/jniLibs/arm64-v8a/
          cp target/aarch64-linux-android/release/pinitd android/app/src/main/jniLibs/arm64-v8a/libpinitd.so

      - name: Grant execute permission for gradlew
        run: |
          cd android
          chmod +x gradlew

      - name: Generate version for build
        run: |
          TODAY=$(date +'%Y-%m-%d')
          TODAY_CODE=$(date +'%Y%m%d')

          # Get all existing releases for today (fetch more to avoid pagination issues)
          EXISTING=$(gh release list --limit 100 --json tagName --jq '.[].tagName' | grep "^${TODAY}\." || echo "")

          if [ -z "$EXISTING" ]; then
            # No releases today, start with .0
            BUILD_NUM=0
          else
            # Find highest build number for today
            BUILD_NUM=$(echo "$EXISTING" | sed "s/^${TODAY}\.//" | sort -n | tail -1)
            BUILD_NUM=$((BUILD_NUM + 1))
          fi

          echo "Existing releases for ${TODAY}: $EXISTING"
          echo "Next build number: $BUILD_NUM"

          VERSION_NAME="${TODAY}.${BUILD_NUM}"
          VERSION_CODE="${TODAY_CODE}${BUILD_NUM}"

          echo "Generated version name: $VERSION_NAME"
          echo "Generated version code: $VERSION_CODE"

          # Set environment variables for subsequent steps
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV
          echo "VERSION_CODE=$VERSION_CODE" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build main APK
        run: |
          cd android
          ./gradlew assembleRelease -PversionName="$VERSION_NAME" -PversionCode="$VERSION_CODE"

      - name: Rename APK files and copy binaries
        run: |
          # Create release artifacts directory
          mkdir -p release-artifacts

          # Copy main APK
          cp android/app/build/outputs/apk/release/app-release.apk release-artifacts/PenumbraOS-pinitd-${VERSION_NAME}.apk

          # Copy pinitd-cli binary
          cp target/aarch64-linux-android/release/pinitd-cli release-artifacts/pinitd-cli

      - name: Create Prerelease
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION_NAME }}
          name: Alpha ${{ env.VERSION_NAME }}
          prerelease: true
          generate_release_notes: true
          files: release-artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
